import React from 'react';
import { Box, Text, useTheme } from 'src/ink.js';
import { env } from '../../utils/env.js';
const WELCOME_V2_WIDTH = 58;
export function WelcomeV2() {
  const [theme] = useTheme();
  if (env.terminal === "Apple_Terminal") {
    return <AppleTerminalWelcomeV2 theme={theme} welcomeMessage="Welcome to clpzcode" />;
  }
  if (["light", "light-daltonized", "light-ansi"].includes(theme)) {
    return <Box width={WELCOME_V2_WIDTH}><Text><Text><Text color="claude">{"Welcome to clpzcode"} </Text><Text dimColor={true}>v{MACRO.DISPLAY_VERSION ?? MACRO.VERSION} </Text></Text><Text>{"…………………………………………………………………………………………………………………………………………………………"}</Text><Text>{"                                                          "}</Text><Text>{"                                                          "}</Text><Text>{"                                                          "}</Text><Text>{"            ░░░░░░                                        "}</Text><Text>{"    ░░░   ░░░░░░░░░░                                      "}</Text><Text>{"   ░░░░░░░░░░░░░░░░░░░                                    "}</Text><Text>{"                                                          "}</Text><Text><Text dimColor={true}>{"                           ░░░░"}</Text><Text>{"                     ██    "}</Text></Text><Text><Text dimColor={true}>{"                         ░░░░░░░░░░"}</Text><Text>{"               ██▒▒██  "}</Text></Text><Text>{"                                            ▒▒      ██   ▒"}</Text><Text>{"      "}<Text color="clawd_body"> █████████ </Text>{"                         ▒▒░░▒▒      ▒ ▒▒"}</Text><Text>{"      "}<Text color="clawd_body" backgroundColor="clawd_background">██▄█████▄██</Text>{"                           ▒▒         ▒▒ "}</Text><Text>{"      "}<Text color="clawd_body"> █████████ </Text>{"                          ░          ▒   "}</Text><Text>{"…………………"}<Text color="clawd_body">{"█ █   █ █"}</Text>{"……………………………………………………………………░…………………………▒…………"}</Text></Text></Box>;
  }
  return <Box width={WELCOME_V2_WIDTH}><Text><Text><Text color="claude">{"Welcome to clpzcode"} </Text><Text dimColor={true}>v{MACRO.DISPLAY_VERSION ?? MACRO.VERSION} </Text></Text><Text>{"…………………………………………………………………………………………………………………………………………………………"}</Text><Text>{"                                                          "}</Text><Text>{"     *                                       █████▓▓░     "}</Text><Text>{"                                 *         ███▓░     ░░   "}</Text><Text>{"            ░░░░░░                        ███▓░           "}</Text><Text>{"    ░░░   ░░░░░░░░░░                      ███▓░           "}</Text><Text><Text>{"   ░░░░░░░░░░░░░░░░░░░    "}</Text><Text bold={true}>*</Text><Text>{"                ██▓░░      ▓   "}</Text></Text><Text>{"                                             ░▓▓███▓▓░    "}</Text><Text dimColor={true}>{" *                                 ░░░░                   "}</Text><Text dimColor={true}>{"                                 ░░░░░░░░                 "}</Text><Text dimColor={true}>{"                               ░░░░░░░░░░░░░░░░           "}</Text><Text>{"      "}<Text color="clawd_body"> █████████ </Text>{"                                       "}<Text dimColor={true}>*</Text><Text> </Text></Text><Text>{"      "}<Text color="clawd_body">██▄█████▄██</Text><Text>{"                        "}</Text><Text bold={true}>*</Text><Text>{"                "}</Text></Text><Text>{"      "}<Text color="clawd_body"> █████████ </Text>{"     *                                   "}</Text><Text>{"…………………"}<Text color="clawd_body">{"█ █   █ █"}</Text>{"………………………………………………………………………………………………………………"}</Text></Text></Box>;
}
type AppleTerminalWelcomeV2Props = {
  theme: string;
  welcomeMessage: string;
};
function AppleTerminalWelcomeV2({ theme, welcomeMessage }: AppleTerminalWelcomeV2Props) {
  const isLightTheme = ["light", "light-daltonized", "light-ansi"].includes(theme);
  if (isLightTheme) {
    const title = <Text><Text color="claude">{welcomeMessage} </Text><Text dimColor={true}>v{MACRO.DISPLAY_VERSION ?? MACRO.VERSION} </Text></Text>;
    return <Box width={WELCOME_V2_WIDTH}><Text>{title}<Text>{"…………………………………………………………………………………………………………………………………………………………"}</Text><Text>{"                                                          "}</Text><Text>{"                                                          "}</Text><Text>{"                                                          "}</Text><Text>{"            ░░░░░░                                        "}</Text><Text>{"    ░░░   ░░░░░░░░░░                                      "}</Text><Text>{"   ░░░░░░░░░░░░░░░░░░░                                    "}</Text><Text>{"                                                          "}</Text><Text><Text dimColor={true}>{"                           ░░░░"}</Text><Text>{"                     ██    "}</Text></Text><Text><Text dimColor={true}>{"                         ░░░░░░░░░░"}</Text><Text>{"               ██▒▒██  "}</Text></Text><Text>{"                                            ▒▒      ██   ▒"}</Text><Text>{"                                          ▒▒░░▒▒      ▒ ▒▒"}</Text><Text>{"      "}<Text color="clawd_body">▗</Text><Text color="clawd_background" backgroundColor="clawd_body">{" "}▗{"     "}▖{" "}</Text><Text color="clawd_body">▖</Text>{"                           ▒▒         ▒▒ "}</Text><Text>{"       "}<Text backgroundColor="clawd_body">{" ".repeat(9)}</Text>{"                           ░          ▒   "}</Text><Text>{"…………………"}<Text backgroundColor="clawd_body"> </Text><Text> </Text><Text backgroundColor="clawd_body"> </Text><Text>{"   "}</Text><Text backgroundColor="clawd_body"> </Text><Text> </Text><Text backgroundColor="clawd_body"> </Text>{"……………………………………………………………………░…………………………▒…………"}</Text></Text></Box>;
  }
  const title = <Text><Text color="claude">{welcomeMessage} </Text><Text dimColor={true}>v{MACRO.DISPLAY_VERSION ?? MACRO.VERSION} </Text></Text>;
  return <Box width={WELCOME_V2_WIDTH}><Text>{title}<Text>{"…………………………………………………………………………………………………………………………………………………………"}</Text><Text>{"                                                          "}</Text><Text>{"     *                                       █████▓▓░     "}</Text><Text>{"                                 *         ███▓░     ░░   "}</Text><Text>{"            ░░░░░░                        ███▓░           "}</Text><Text>{"    ░░░   ░░░░░░░░░░                      ███▓░           "}</Text><Text><Text>{"   ░░░░░░░░░░░░░░░░░░░    "}</Text><Text bold={true}>*</Text><Text>{"                ██▓░░      ▓   "}</Text></Text><Text>{"                                             ░▓▓███▓▓░    "}</Text><Text dimColor={true}>{" *                                 ░░░░                   "}</Text><Text dimColor={true}>{"                                 ░░░░░░░░                 "}</Text><Text dimColor={true}>{"                               ░░░░░░░░░░░░░░░░           "}</Text><Text>{"                                                      "}<Text dimColor={true}>*</Text><Text> </Text></Text><Text>{"        "}<Text color="clawd_body">▗</Text><Text color="clawd_background" backgroundColor="clawd_body">{" "}▗{"     "}▖{" "}</Text><Text color="clawd_body">▖</Text><Text>{"                       "}</Text><Text bold={true}>*</Text><Text>{"                "}</Text></Text><Text>{"        "}<Text backgroundColor="clawd_body">{" ".repeat(9)}</Text>{"      *                                   "}</Text><Text>{"…………………"}<Text backgroundColor="clawd_body"> </Text><Text> </Text><Text backgroundColor="clawd_body"> </Text><Text>{"   "}</Text><Text backgroundColor="clawd_body"> </Text><Text> </Text><Text backgroundColor="clawd_body"> </Text>{"………………………………………………………………………………………………………………"}</Text></Text></Box>;
}
